export const sampleItems = [
    {
        itemId: 1,
        itemName: 'FCLUSLL 18Pcs Car Wash Cleaning Kit',
        price: 39.99,
        discount: 1,
        subdepartmentId: 1,
        options:[{
          name: 'Size',
          choices:[{
            choiceId: 1,
            name: '18Pcs',
            price: 39.99
          },
          {
            choiceId: 2,
            name: '23Pcs',
            price: 45.99
          }
        ]
        }],
        ratings: 4.2,
        ratingCount: 23,
        about: 'Keep Your Car Clean: The grit trap at the bottom of the car wash bucket is effective in reducing swirls that occur during car washes.'
    },
    {
      itemId: 2,
      itemName: 'Item 2',
      price: 18,
      discount: 0.9,
      subdepartmentId: 2,
      options:[],
      ratings: 4.3,
      ratingCount: 92,
      about: 'About text',
    },
    {
      itemId: 3,
      itemName: 'Cotton',
      price: 38,
      discount: 0.6,
      subdepartmentId: 4,
      options:[],
      ratings: 3.8,
      ratingCount: 11,
      about: 'About text'
    },
    {
      itemId: 4,
      itemName: 'Water 2',
      price: 8,
      discount: 1,
      subdepartmentId: 5,
      options:[],
      ratings: 4.4,
      ratingCount: 31,
      about: 'About text'
    },
    {
      itemId: 5,
      itemName: 'Paper 2',
      price: 10,
      discount: 0.8,
      subdepartmentId: 5,
      options:[],
      ratings: 4.6,
      ratingCount: 31,
      about: 'About text'
    },
    {
      itemId: 6,
      itemName: 'Test 3',
      price: 10,
      discount: 0.8,
      subdepartmentId: 2,
      options:[],
      ratings: 4.8,
      ratingCount: 31,
      about: 'About text'
    },
    {
      itemId: 7,
      itemName: '13 3',
      price: 99,
      discount: 1,
      subdepartmentId: 7,
      options:[],
      ratings: 2.8,
      ratingCount: 1231,
      about: 'About text'
    },
    {
      itemId: 8,
      itemName: '13 3',
      price: 99,
      discount: 1,
      subdepartmentId: 9,
      options:[],
      ratings: 3.3,
      ratingCount: 1231,
      about: 'About text'
    },
    {
      itemId: 9,
      itemName: 'doiwahd',
      price: 99,
      discount: 1,
      subdepartmentId: 1,
      options:[],
      ratings: 3.8,
      ratingCount: 1231,
      about: 'About text'
    },
    {
      itemId: 10,
      itemName: 'ggs',
      price: 99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.8,
      ratingCount: 1231,
      about: 'About text'
    },
    {
      itemId: 11,
      itemName: 'exicite',
      price: 99,
      discount: 1,
      subdepartmentId: 3,
      options:[],
      ratings: 3.8,
      ratingCount: 1231,
      about: 'About text'
    },
    {
      itemId: 12,
      itemName: 'Six',
      price: 99,
      discount: 1,
      subdepartmentId: 6,
      options:[],
      ratings: 3.5,
      ratingCount: 1231,
      about: 'About text'
    },
    {
      itemId: 13,
      itemName: 'Six 2',
      price: 102,
      discount: 1,
      subdepartmentId: 6,
      options:[],
      ratings: 5,
      ratingCount: 14,
      about: 'About text'
    },
    {
      itemId: 14,
      itemName: 'Four 2',
      price: 99.99,
      discount: 1,
      subdepartmentId: 4,
      options:[],
      ratings: 3,
      ratingCount: 15,
      about: 'About text'
    },
    {
      itemId: 15,
      itemName: 'Nine 2',
      price: 199.99,
      discount: 1,
      subdepartmentId: 9,
      options:[],
      ratings: 4.2,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 16,
      itemName: 'Scream out 2',
      price: 199.99,
      discount: 1,
      subdepartmentId: 3,
      options:[],
      ratings: 4.6,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 17,
      itemName: 'wastib out 2',
      price: 199.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 4.2,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 18,
      itemName: 'chil out 2',
      price: 199.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 4.2,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 19,
      itemName: 'bro 2',
      price: 2.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 4.2,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 20,
      itemName: 'loud 2',
      price: 2.29,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.2,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 21,
      itemName: 'so loud 2',
      price: 2.29,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 22,
      itemName: 'cock 2',
      price: 172,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.7,
      ratingCount: 57,
      about: 'About text'
    },
    {
      itemId: 23,
      itemName: 'cock 3',
      price: 621,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 4,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 24,
      itemName: 'cock 4',
      price: 20,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 25,
      itemName: 'lule',
      price: 48,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 4.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 26,
      itemName: '781',
      price: 64,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.6,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 27,
      itemName: '781',
      price: 64,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.6,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 28,
      itemName: 'xdd',
      price: 3.21,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 4.2,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 29,
      itemName: 'noiiii',
      price: 45,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 4.6,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 30,
      itemName: 'ok',
      price: 88.8,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 31,
      itemName: 'dude',
      price: 45.8,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 2.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 32,
      itemName: 'what',
      price: 9.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 1.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 33,
      itemName: 'hahalol',
      price: 19.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 0.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 34,
      itemName: 'blahblahbalh',
      price: 49.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 2.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 35,
      itemName: 'blaha',
      price: 7.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 36,
      itemName: 'blaha',
      price: 7.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 37,
      itemName: 'blaha',
      price: 7.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 38,
      itemName: 'blaha',
      price: 7.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 39,
      itemName: 'blaha',
      price: 7.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 40,
      itemName: 'blaha',
      price: 7.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 41,
      itemName: 'blaha',
      price: 7.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 42,
      itemName: 'blaha',
      price: 7.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 43,
      itemName: 'blaha',
      price: 7.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 44,
      itemName: 'blaha',
      price: 7.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 45,
      itemName: 'blaha',
      price: 7.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 46,
      itemName: 'blaha',
      price: 7.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 47,
      itemName: 'blaha',
      price: 7.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 48,
      itemName: 'blaha',
      price: 7.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 49,
      itemName: 'blaha',
      price: 7.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.5,
      ratingCount: 37,
      about: 'About text'
    },
    {
      itemId: 50,
      itemName: 'blaha',
      price: 7.99,
      discount: 1,
      subdepartmentId: 2,
      options:[],
      ratings: 3.5,
      ratingCount: 37,
      about: 'About text'
    }
  ]